from __future__ import annotations


def demo_page() -> str:
    return '''<!doctype html>
<html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Monitoring & LLMOps Demo</title>
<style>
:root{color-scheme:dark;--bg:#0a1020;--card:#16213a;--line:#31405f;--text:#edf3ff;--muted:#a9b8d2;--accent:#67e8b4}
*{box-sizing:border-box}body{margin:0;background:linear-gradient(130deg,#0a1020,#142039);color:var(--text);font:16px Segoe UI,Arial,sans-serif}
main{max-width:1250px;margin:auto;padding:26px}header{display:flex;justify-content:space-between;align-items:center;gap:16px}h1{margin:0}p{color:var(--muted);line-height:1.5}
nav{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0}button{background:#213351;color:var(--text);border:1px solid var(--line);border-radius:9px;padding:10px 14px;cursor:pointer}button:hover,button.active{border-color:var(--accent)}
.tab{display:none}.tab.active{display:block}.panel,.card{background:var(--card);border:1px solid var(--line);border-radius:14px;padding:18px;margin-bottom:14px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.card{margin:0}.card strong{display:block;font-size:26px;margin-top:7px}.label{color:var(--muted);font-size:13px}
.row{display:flex;gap:12px;flex-wrap:wrap}.row label{flex:1;min-width:150px}input,textarea,select{display:block;width:100%;background:#0d1629;color:var(--text);border:1px solid var(--line);border-radius:8px;padding:10px;margin:7px 0 15px}textarea{height:100px}table{width:100%;border-collapse:collapse;font-size:13px}td,th{padding:8px;border-bottom:1px solid var(--line);text-align:left}pre{white-space:pre-wrap;overflow:auto;background:#0d1629;padding:13px;border-radius:8px}a{color:#93c5fd}.pill{border:1px solid #38836a;border-radius:20px;padding:8px;color:var(--accent)}.flow{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.flow div{border:1px solid var(--line);padding:15px;border-radius:9px;text-align:center}li{margin:10px 0}@media(max-width:700px){.grid,.flow{grid-template-columns:1fr 1fr}header{display:block}}@media(max-width:450px){.grid,.flow{grid-template-columns:1fr}}
</style></head><body><main>
<header><div><h1>Monitoring & LLMOps Demo</h1><p>Metrics → Logs → Traces → Root cause</p></div><span id="status" class="pill">Đang tải...</span></header>
<nav><button class="active" data-tab="chat">Chat demo</button><button data-tab="observe">Observability</button><button data-tab="incident">Incident walkthrough</button><button data-tab="guide">Presentation guide</button></nav>
<section id="chat" class="tab active"><div class="panel"><h2>Gửi một request AI</h2><p>Request tạo log, metrics và trace. Thử câu hỏi chứa “monitoring”, “refund” hoặc “policy”.</p>
<div class="row"><label>User ID<input id="user" value="demo-student"></label><label>Session ID<input id="session" value="demo-session-01"></label><label>Feature<select id="feature"><option>qa</option><option>summary</option></select></label></div>
<label>Câu hỏi<textarea id="message">Explain monitoring and why metrics, logs, and traces are connected.</textarea></label><button id="send">Gửi request</button><div id="answer" class="panel" hidden></div></div></section>
<section id="observe" class="tab"><div class="panel"><h2>6 panel từ structured logs</h2><p>Cửa sổ 60 phút. Mỗi panel có threshold trong config/dashboard.yaml.</p><div id="cards" class="grid"></div></div><div class="panel"><h2>Recent logs</h2><p>Lấy correlation ID ở đây rồi tìm trace cùng mã trong Langfuse.</p><div style="overflow:auto"><table><thead><tr><th>Event</th><th>Correlation ID</th><th>Feature</th><th>Latency</th><th>Cost</th></tr></thead><tbody id="logs"></tbody></table></div></div></section>
<section id="incident" class="tab"><div class="panel"><h2>Incident practice</h2><p>Bật một triệu chứng, gửi lại câu hỏi, so sánh metrics, tìm log, rồi xem span trên Langfuse. Challenge chính thức chỉ dùng file Lab Coach cấp.</p><button data-scenario="rag_slow">Bật RAG chậm</button> <button data-scenario="tool_fail">Bật retrieval lỗi</button> <button data-scenario="cost_spike">Bật cost spike</button> <button id="disable">Tắt tất cả</button><pre id="incident-state"></pre><div class="flow"><div>1. Metrics<br><small>Triệu chứng</small></div><div>2. Logs<br><small>Request ID</small></div><div>3. Traces<br><small>Span chậm/lỗi</small></div><div>4. Root cause<br><small>Fix + prevention</small></div></div></div></section>
<section id="guide" class="tab"><div class="panel"><h2>Kịch bản thuyết trình 3–5 phút</h2><ol><li>Giới thiệu API fake LLM và mục tiêu quan sát hệ thống AI.</li><li>Gửi một câu hỏi. Chỉ correlation ID, latency, token, cost.</li><li>Xem 6 panel: latency/TTFT, traffic, errors/retrieval, cost, tokens, quality.</li><li>Mở Langfuse: chỉ root trace, retrieval span, generation span.</li><li>Bật RAG chậm. Dùng Metrics → Logs → Traces để tìm nguyên nhân.</li><li>Giải thích prompt version/rollback, SLO 99.5%, error budget 0.5% và ba alerts.</li></ol><h3>Câu trả lời ngắn</h3><p>Metrics cho biết triệu chứng; logs chỉ request bị ảnh hưởng; trace cho biết bước nào chậm hoặc lỗi. Correlation ID nối cả ba. Langfuse giữ trace và prompt versions; file logs.jsonl là nguồn structured log và dashboard.</p><a id="langfuse-link" target="_blank" rel="noopener noreferrer" href="https://cloud.langfuse.com">Mở Langfuse</a></div></section>
</main><script>
const $=id=>document.getElementById(id);const cell=(row,value)=>{const td=document.createElement('td');td.textContent=value??'';row.appendChild(td)};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab));refresh()});
async function refresh(){try{const d=await(await fetch('/demo/summary')).json();$('status').textContent=d.tracing_enabled?'Langfuse tracing ON':'Local fallback';$('langfuse-link').href=d.langfuse_base_url;const m=d.metrics;const panels=[['Latency P50/P95/P99 + TTFT P95',`${m.latency_p50}/${m.latency_p95}/${m.latency_p99} ms · TTFT ${m.ttft_p95} ms`,'P95 ≤ 3000 ms'],['Traffic',`${m.traffic} requests · ${m.rate_per_minute}/min`,'≥ 1 req/min'],['Errors + retrieval',`${m.error_rate_pct}% errors · ${m.retrieval_success_rate_pct}% retrieval success`,'Error rate ≤ 2%'],['Cost',`$${m.total_cost_usd}`,'Total ≤ $2.5'],['Tokens',`${m.tokens_in_total} in / ${m.tokens_out_total} out`,'≤ 50000 tokens'],['Quality',`${m.quality_avg}`,'Mean ≥ 0.75']];$('cards').replaceChildren(...panels.map(p=>{let x=document.createElement('div');x.className='card';let a=document.createElement('span');a.className='label';a.textContent=p[0];let b=document.createElement('strong');b.textContent=p[1];let c=document.createElement('small');c.textContent=p[2];x.append(a,b,c);return x}));$('logs').replaceChildren(...d.recent_logs.slice(-20).reverse().map(x=>{let tr=document.createElement('tr');[x.event,x.correlation_id,x.feature,x.latency_ms,x.cost_usd].forEach(v=>cell(tr,v));return tr}));$('incident-state').textContent=JSON.stringify((await(await fetch('/health')).json()).incidents,null,2)}catch(e){$('status').textContent='API unavailable'}}
$('send').onclick=async()=>{const box=$('answer');box.hidden=false;box.textContent='Đang gửi...';try{const r=await fetch('/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_id:$('user').value,session_id:$('session').value,feature:$('feature').value,message:$('message').value})});const d=await r.json();box.textContent=`HTTP ${r.status} | ${d.answer||d.detail} | correlation_id=${d.correlation_id||'—'} | latency=${d.latency_ms||'—'} ms | tokens=${d.tokens_in||'—'}/${d.tokens_out||'—'} | cost=$${d.cost_usd||'—'}`;refresh()}catch(e){box.textContent=String(e)}};
document.querySelectorAll('[data-scenario]').forEach(b=>b.onclick=async()=>{await fetch('/incidents/'+b.dataset.scenario+'/enable',{method:'POST'});refresh()});$('disable').onclick=async()=>{for(const n of ['rag_slow','tool_fail','cost_spike'])await fetch('/incidents/'+n+'/disable',{method:'POST'});refresh()};refresh();setInterval(refresh,30000);
</script></body></html>'''
